// <auto-generated />
using System;
using GBC_Travel_Group23.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBC_Travel_Group23.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240226191406_Update_1")]
    partial class Update_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GBC_Travel_Group23.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.CarRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CarYear")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("CarRentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5,
                            CarYear = 2020,
                            Count = 15,
                            LocationId = 1001,
                            Make = "Toyota",
                            Model = "Camry",
                            Rate = 75.0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 7,
                            CarYear = 2019,
                            Count = 10,
                            LocationId = 1002,
                            Make = "Ford",
                            Model = "Explorer",
                            Rate = 85.0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 8,
                            CarYear = 2021,
                            Count = 12,
                            LocationId = 1003,
                            Make = "Chevrolet",
                            Model = "Suburban",
                            Rate = 90.0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 12,
                            CarYear = 2020,
                            Count = 5,
                            LocationId = 1004,
                            Make = "Mercedes-Benz",
                            Model = "Sprinter",
                            Rate = 120.0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 5,
                            CarYear = 2018,
                            Count = 20,
                            LocationId = 1005,
                            Make = "Honda",
                            Model = "Accord",
                            Rate = 60.0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 5,
                            CarYear = 2022,
                            Count = 10,
                            LocationId = 1006,
                            Make = "Jeep",
                            Model = "Grand Cherokee",
                            Rate = 80.0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 8,
                            CarYear = 2019,
                            Count = 8,
                            LocationId = 1007,
                            Make = "Nissan",
                            Model = "Armada",
                            Rate = 95.0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 8,
                            CarYear = 2021,
                            Count = 12,
                            LocationId = 1008,
                            Make = "Hyundai",
                            Model = "Palisade",
                            Rate = 100.0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 5,
                            CarYear = 2020,
                            Count = 7,
                            LocationId = 1009,
                            Make = "BMW",
                            Model = "X5",
                            Rate = 110.0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 7,
                            CarYear = 2022,
                            Count = 9,
                            LocationId = 1010,
                            Make = "Audi",
                            Model = "Q7",
                            Rate = 130.0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 8,
                            CarYear = 2021,
                            Count = 6,
                            LocationId = 1011,
                            Make = "Kia",
                            Model = "Telluride",
                            Rate = 90.0
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 8,
                            CarYear = 2019,
                            Count = 4,
                            LocationId = 1012,
                            Make = "Lexus",
                            Model = "LX",
                            Rate = 150.0
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 7,
                            CarYear = 2020,
                            Count = 10,
                            LocationId = 1013,
                            Make = "Volkswagen",
                            Model = "Atlas",
                            Rate = 85.0
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 5,
                            CarYear = 2021,
                            Count = 18,
                            LocationId = 1014,
                            Make = "Subaru",
                            Model = "Outback",
                            Rate = 70.0
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 7,
                            CarYear = 2022,
                            Count = 5,
                            LocationId = 1015,
                            Make = "Tesla",
                            Model = "Model X",
                            Rate = 200.0
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 7,
                            CarYear = 2020,
                            Count = 12,
                            LocationId = 1016,
                            Make = "Mazda",
                            Model = "CX-9",
                            Rate = 80.0
                        });
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Email = "fcottem0@linkedin.com",
                            FullName = "Frederica Cottem",
                            Phone = "+7 (375) 654-3590"
                        },
                        new
                        {
                            Id = 10002,
                            Email = "acomellini1@cnet.com",
                            FullName = "Annabella Comellini",
                            Phone = "+93 (923) 606-7690"
                        },
                        new
                        {
                            Id = 10003,
                            Email = "rdaniel2@sfgate.com",
                            FullName = "Redd Daniel",
                            Phone = "+86 (422) 538-4788"
                        },
                        new
                        {
                            Id = 10004,
                            Email = "tbister3@so-net.ne.jp",
                            FullName = "Tana Bister",
                            Phone = "+7 (528) 881-6250"
                        },
                        new
                        {
                            Id = 10005,
                            Email = "nboulder4@cisco.com",
                            FullName = "Nikaniki Boulder",
                            Phone = "+93 (657) 895-3488"
                        },
                        new
                        {
                            Id = 10006,
                            Email = "aplaide5@smh.com.au",
                            FullName = "Ariana Plaide",
                            Phone = "+57 (863) 320-2637"
                        },
                        new
                        {
                            Id = 10007,
                            Email = "blivzey6@businessweek.com",
                            FullName = "Burr Livzey",
                            Phone = "+675 (218) 591-6032"
                        },
                        new
                        {
                            Id = 10008,
                            Email = "wbarrow7@arstechnica.com",
                            FullName = "Waring Barrow",
                            Phone = "+86 (398) 693-2908"
                        },
                        new
                        {
                            Id = 10009,
                            Email = "bbrymham8@usgs.gov",
                            FullName = "Brade Brymham",
                            Phone = "+55 (979) 581-5768"
                        });
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArrivalLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureLocationId")
                        .HasColumnType("int");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plane")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalLocationId");

                    b.HasIndex("DepartureLocationId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            Amenities = "Free Wi-Fi, Pool, Gym",
                            LocationId = 1001,
                            Name = "Luxury Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue",
                            Amenities = "Breakfast, Parking, Pet Friendly",
                            LocationId = 1002,
                            Name = "Comfort Inn"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Road",
                            Amenities = "Spa, Restaurant, Conference Rooms",
                            LocationId = 1003,
                            Name = "Grand Resort"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Skyline Boulevard",
                            Amenities = "City View, Rooftop Bar",
                            LocationId = 1004,
                            Name = "Cityscape Suites"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Beachfront Avenue",
                            Amenities = "Beach Access, Ocean View",
                            LocationId = 1005,
                            Name = "Seaside Retreat"
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Summit Drive",
                            Amenities = "Hiking Trails, Fireplace",
                            LocationId = 1006,
                            Name = "Mountain Lodge"
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Downtown Street",
                            Amenities = "Modern Decor, Lounge",
                            LocationId = 1007,
                            Name = "Urban Oasis Hotel"
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 Serene Road",
                            Amenities = "Garden, Reading, Room",
                            LocationId = 1008,
                            Name = "Tranquil Inn"
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Heritage Lane",
                            Amenities = "Antique Furnishings, Ballroom",
                            LocationId = 1009,
                            Name = "Historic Mansion Hotel"
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Maple Court",
                            Amenities = "Kid's Play Area, Family-Friendly",
                            LocationId = 1010,
                            Name = "Family Suites"
                        },
                        new
                        {
                            Id = 11,
                            Address = "808 Business Plaza",
                            Amenities = "Business Center, Concierge",
                            LocationId = 1011,
                            Name = "Executive Stay"
                        },
                        new
                        {
                            Id = 12,
                            Address = "909 Forest Path",
                            Amenities = "Nature Trails, Bird Watching",
                            LocationId = 1012,
                            Name = "Woodland Lodge"
                        },
                        new
                        {
                            Id = 13,
                            Address = "1001 Grand Avenue",
                            Amenities = "Luxurious Spa, Fine Dining",
                            LocationId = 1013,
                            Name = "Elegant Plaza Hotel"
                        },
                        new
                        {
                            Id = 14,
                            Address = "1102 Waterfront Road",
                            Amenities = "River View, Fishing Dock",
                            LocationId = 1014,
                            Name = "Riverside Inn"
                        },
                        new
                        {
                            Id = 15,
                            Address = "1203 Cozy Lane",
                            Amenities = "Charming Decor, Quiet Atmosphere",
                            LocationId = 1015,
                            Name = "Quaint Cottage Hotel"
                        });
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.HotelRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("MaxOccupants")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            AirportCode = "JFK",
                            City = "New York",
                            Country = "USA",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 1002,
                            AirportCode = "YYZ",
                            City = "Toronto",
                            Country = "Canada",
                            Region = "ON"
                        },
                        new
                        {
                            Id = 1003,
                            AirportCode = "JFK",
                            City = "New York",
                            Country = "USA",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 1004,
                            AirportCode = "YYZ",
                            City = "Toronto",
                            Country = "Canada",
                            Region = "ON"
                        },
                        new
                        {
                            Id = 1005,
                            AirportCode = "LHR",
                            City = "London",
                            Country = "United Kingdom",
                            Region = "ENG"
                        },
                        new
                        {
                            Id = 1006,
                            AirportCode = "TXL",
                            City = "Berlin",
                            Country = "Germany",
                            Region = "BE"
                        },
                        new
                        {
                            Id = 1007,
                            AirportCode = "HND",
                            City = "Tokyo",
                            Country = "Japan",
                            Region = "13"
                        },
                        new
                        {
                            Id = 1008,
                            AirportCode = "SYD",
                            City = "Sydney",
                            Country = "Australia",
                            Region = "NSW"
                        },
                        new
                        {
                            Id = 1009,
                            AirportCode = "GIG",
                            City = "Rio de Janeiro",
                            Country = "Brazil",
                            Region = "RJ"
                        },
                        new
                        {
                            Id = 1010,
                            AirportCode = "CPT",
                            City = "Cape Town",
                            Country = "South Africa",
                            Region = "WC"
                        },
                        new
                        {
                            Id = 1011,
                            AirportCode = "BOM",
                            City = "Mumbai",
                            Country = "India",
                            Region = "MH"
                        },
                        new
                        {
                            Id = 1012,
                            AirportCode = "PEK",
                            City = "Beijing",
                            Country = "China",
                            Region = "BJ"
                        },
                        new
                        {
                            Id = 1013,
                            AirportCode = "CDG",
                            City = "Paris",
                            Country = "France",
                            Region = "IDF"
                        },
                        new
                        {
                            Id = 1014,
                            AirportCode = "FCO",
                            City = "Rome",
                            Country = "Italy",
                            Region = "RM"
                        },
                        new
                        {
                            Id = 1015,
                            AirportCode = "BCN",
                            City = "Barcelona",
                            Country = "Spain",
                            Region = "CT"
                        },
                        new
                        {
                            Id = 1016,
                            AirportCode = "SVO",
                            City = "Moscow",
                            Country = "Russia",
                            Region = "MOW"
                        },
                        new
                        {
                            Id = 1017,
                            AirportCode = "ICN",
                            City = "Seoul",
                            Country = "South Korea",
                            Region = "11"
                        });
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Booking", b =>
                {
                    b.HasOne("GBC_Travel_Group23.Models.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBC_Travel_Group23.Models.CarRental", "CarRental")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBC_Travel_Group23.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBC_Travel_Group23.Models.HotelRoom", "HotelRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarRental");

                    b.Navigation("Client");

                    b.Navigation("Flight");

                    b.Navigation("HotelRoom");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.CarRental", b =>
                {
                    b.HasOne("GBC_Travel_Group23.Models.Location", "Location")
                        .WithMany("CarRentals")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Flight", b =>
                {
                    b.HasOne("GBC_Travel_Group23.Models.Location", "ArrivalLocation")
                        .WithMany("ArrivalFlights")
                        .HasForeignKey("ArrivalLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBC_Travel_Group23.Models.Location", "DepartureLocation")
                        .WithMany("DepartureFlights")
                        .HasForeignKey("DepartureLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalLocation");

                    b.Navigation("DepartureLocation");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Hotel", b =>
                {
                    b.HasOne("GBC_Travel_Group23.Models.Location", "Location")
                        .WithMany("Hotels")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.HotelRoom", b =>
                {
                    b.HasOne("GBC_Travel_Group23.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.CarRental", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.HotelRoom", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GBC_Travel_Group23.Models.Location", b =>
                {
                    b.Navigation("ArrivalFlights");

                    b.Navigation("CarRentals");

                    b.Navigation("DepartureFlights");

                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
